# CODSOFT Internship - Task 1

## Data Cleaning and Preparation using Pandas

### Objective

The objective of this task is to import an employee dataset using Python and Pandas, inspect its structure, identify missing values, duplicate records, and inconsistent data entries, clean the dataset, correct data types, and prepare the data for further analysis.

### Tasks Performed

- Import the dataset using Pandas
- Inspect the dataset structure
- Identify missing values
- Identify duplicate records
- Identify inconsistent data entries
- Handle missing values
- Remove duplicate records
- Correct data types
- Standardize inconsistent values
- Export the cleaned dataset as a CSV file

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("CODSOFT_Task1_Employee_Data_500.xlsx")
print("dataset loaded successfully")

dataset loaded successfully

In [5]:
df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
0,1,Tanvi Singh,22,Male,Operations,Gurugram,54256,2019-07-26,11,tanvi.singh1@company.com,Excellent
1,2,Vivek Mehta,26,Male,Sales,Lucknow,28905,2019-01-19,3,vivek.mehta2@company.com,Good
2,3,Rohan Patel,22,Other,Sales,Noida,110181,2025-11-12,8,rohan.patel3@company.com,Needs Improvement
3,4,Diya Negi,38,Male,Data Analytics,Delhi,116506,2022-09-28,5,diya.negi4@company.com,Average
4,5,Avni Gupta,42,Female,IT,Dehradun,37676,2022-01-10,5,avni.gupta5@company.com,Average

In [6]:
df.tail()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
495,206,Khushi Joshi,36,Other,IT,Delhi,49385,2023-08-07,8,khushi.joshi206@company.com,Needs Improvement
496,248,Kavya Patel,27,Female,Finance,Gurugram,109058,2024-02-04,8,kavya.patel248@company.com,Needs Improvement
497,302,Vivek Rawat,31,Female,HR,Gurugram,60180,2023-07-13,2,vivek.rawat302@company.com,Excellent
498,378,Zoya Patel,23,Male,HR,Chandigarh,36955,2025-12-22,3,zoya.patel378@company.com,Average
499,445,Tanvi Verma,41,Male,Operations,Delhi,84251,2021-01-25,3,tanvi.verma445@company.com,Good

## Inspect Dataset Structure

In [8]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 500
Number of columns: 11

In [9]:
df.columns.tolist()

['Employee_ID',
 'Name',
 'Age',
 'Gender',
 'Department',
 'City',
 'Salary',
 'Joining_Date',
 'Experience_Years',
 'Email',
 'Performance_Rating']

In [10]:
df.dtypes

Employee_ID                    int64
Name                             str
Age                           object
Gender                           str
Department                       str
City                             str
Salary                        object
Joining_Date          datetime64[us]
Experience_Years               int64
Email                            str
Performance_Rating               str
dtype: object

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         500 non-null    int64
 1   Name                500 non-null    str
 2   Age                 490 non-null    object
 3   Gender              500 non-null    str
 4   Department          493 non-null    str
 5   City                500 non-null    str
 6   Salary              490 non-null    object
 7   Joining_Date        494 non-null    datetime64[us]
 8   Experience_Years    500 non-null    int64
 9   Email               500 non-null    str
 10  Performance_Rating  500 non-null    str
dtypes: datetime64[us](1), int64(2), object(2), str(6)
memory usage: 43.1+ KB

In [5]:
df.describe(include="all")

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
count,500.000000,500,490.0,500,493,500,490.0,494,500.000000,500,500
unique,NaN,316,39.0,10,21,19,480.0,NaN,NaN,490,8
top,NaN,Ayush Negi,39.0,Male,Marketing,Dehradun,57591.0,NaN,NaN,vivek.singh26@company.com,Needs Improvement
freq,NaN,5,21.0,176,84,55,2.0,NaN,NaN,2,145
mean,244.648000,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-09 02:28:39.838056,6.106000,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-03 00:00:00,0.000000,NaN,NaN
25%,122.000000,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-09 00:00:00,3.000000,NaN,NaN
50%,244.500000,NaN,NaN,NaN,NaN,NaN,NaN,2022-02-22 12:00:00,6.000000,NaN,NaN
75%,367.250000,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-30 00:00:00,9.000000,NaN,NaN
max,490.000000,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-20 00:00:00,12.000000,NaN,NaN
std,141.541301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.707054,NaN,NaN

## Identify Missing Values

In [12]:
missing_values = df.isnull().sum()
missing_values

Employee_ID            0
Name                   0
Age                   10
Gender                 0
Department             7
City                   0
Salary                10
Joining_Date           6
Experience_Years       0
Email                  0
Performance_Rating     0
dtype: int64

In [11]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Employee_ID           0.0
Name                  0.0
Age                   2.0
Gender                0.0
Department            1.4
City                  0.0
Salary                2.0
Joining_Date          1.2
Experience_Years      0.0
Email                 0.0
Performance_Rating    0.0
dtype: float64

In [13]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0
]

missing_summary

              Missing Values  Percentage
Age                       10         2.0
Department                 7         1.4
Salary                    10         2.0
Joining_Date               6         1.2

## Identify Duplicate Records

In [14]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 10

In [15]:
duplicates = df[df.duplicated(keep=False)]

duplicates

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
25,26,Vivek Singh,24,Male,Marketing,Chandigarh,57591,2020-02-24,3,vivek.singh26@company.com,Needs Improvement
57,58,Arjun Rawat,35,Female,HR,Mumbai,31582,2024-04-02,3,arjun.rawat58@company.com,Excellent
89,90,Gaurav Singh,47,Other,Sales,Bengaluru,54581,2023-11-11,6,gaurav.singh90@company.com,Needs Improvement
121,122,Shivam Joshi,39,Female,IT,Lucknow,26061,2024-05-07,10,shivam.joshi122@company.com,Excellent
153,154,Ayush Kumar,40,Other,Operations,Chandigarh,103148,2018-12-14,0,ayush.kumar154@company.com,Good
205,206,Khushi Joshi,36,Other,IT,Delhi,49385,2023-08-07,8,khushi.joshi206@company.com,Needs Improvement
247,248,Kavya Patel,27,Female,Finance,Gurugram,109058,2024-02-04,8,kavya.patel248@company.com,Needs Improvement
301,302,Vivek Rawat,31,Female,HR,Gurugram,60180,2023-07-13,2,vivek.rawat302@company.com,Excellent
377,378,Zoya Patel,23,Male,HR,Chandigarh,36955,2025-12-22,3,zoya.patel378@company.com,Average
444,445,Tanvi Verma,41,Male,Operations,Delhi,84251,2021-01-25,3,tanvi.verma445@company.com,Good
490,26,Vivek Singh,24,Male,Marketing,Chandigarh,57591,2020-02-24,3,vivek.singh26@company.com,Needs Improvement
491,58,Arjun Rawat,35,Female,HR,Mumbai,31582,2024-04-02,3,arjun.rawat58@company.com,Excellent
492,90,Gaurav Singh,47,Other,Sales,Bengaluru,54581,2023-11-11,6,gaurav.singh90@company.com,Needs Improvement
493,122,Shivam Joshi,39,Female,IT,Lucknow,26061,2024-05-07,10,shivam.joshi122@company.com,Excellent
494,154,Ayush Kumar,40,Other,Operations,Chandigarh,103148,2018-12-14,0,ayush.kumar154@company.com,Good
495,206,Khushi Joshi,36,Other,IT,Delhi,49385,2023-08-07,8,khushi.joshi206@company.com,Needs Improvement
496,248,Kavya Patel,27,Female,Finance,Gurugram,109058,2024-02-04,8,kavya.patel248@company.com,Needs Improvement
497,302,Vivek Rawat,31,Female,HR,Gurugram,60180,2023-07-13,2,vivek.rawat302@company.com,Excellent
498,378,Zoya Patel,23,Male,HR,Chandigarh,36955,2025-12-22,3,zoya.patel378@company.com,Average
499,445,Tanvi Verma,41,Male,Operations,Delhi,84251,2021-01-25,3,tanvi.verma445@company.com,Good

## Identify Inconsistent Entrie

In [16]:
print(df["Department"].unique())

<StringArray>
[    'Operations',          'Sales', 'Data Analytics',             'IT',
             'it',             'HR',        'Finance',      'Marketing',
           ' IT ',              nan,        'finance',      ' Finance ',
             'hr',           ' Hr ',      'marketing',    ' Marketing ',
          'sales',        ' Sales ',     'operations',   ' Operations ',
 'data analytics', 'Data analytics']
Length: 22, dtype: str

In [17]:
df["Department"].value_counts(dropna=False)

Department
Marketing         84
Sales             70
HR                69
Operations        66
IT                66
Finance           65
Data Analytics    59
NaN                7
it                 1
 IT                1
finance            1
 Finance           1
hr                 1
 Hr                1
marketing          1
 Marketing         1
sales              1
 Sales             1
operations         1
 Operations        1
data analytics     1
Data analytics     1
Name: count, dtype: int64

In [18]:
print(df["Gender"].unique())

<StringArray>
[    'Male',    'Other',   'Female',     'male',   ' Male ',   'female',
 ' Female ',        'M',        'F',    'other']
Length: 10, dtype: str

In [19]:
df["Gender"].value_counts(dropna=False)

Gender
Male        176
Female      164
Other       153
male          1
 Male         1
female        1
 Female       1
M             1
F             1
other         1
Name: count, dtype: int64

In [20]:
print(df["City"].unique())

<StringArray>
[  'Gurugram',    'Lucknow',      'Noida',      'Delhi',   'Dehradun',
 'Chandigarh',     'Jaipur',  'Bengaluru',      'delhi',     'Mumbai',
    ' Delhi ',   'Haridwar',   'dehradun', ' Dehradun ',      'NOIDA',
      'noida',   'gurugram', ' Gurugram ',     'mumbai']
Length: 19, dtype: str

In [21]:
df["City"].value_counts(dropna=False)

City
Dehradun      55
Chandigarh    55
Jaipur        55
Gurugram      53
Mumbai        51
Haridwar      50
Noida         45
Lucknow       44
Delhi         42
Bengaluru     41
delhi          1
 Delhi         1
dehradun       1
 Dehradun      1
NOIDA          1
noida          1
gurugram       1
 Gurugram      1
mumbai         1
Name: count, dtype: int64

In [22]:
print(df["Performance_Rating"].unique())

<StringArray>
[        'Excellent',              'Good', 'Needs Improvement',
           'Average',         'excellent',            ' Good ',
           'average', 'NEEDS IMPROVEMENT']
Length: 8, dtype: str

In [23]:
df["Performance_Rating"].value_counts(dropna=False)

Performance_Rating
Needs Improvement    145
Average              127
Good                 116
Excellent            108
excellent              1
 Good                  1
average                1
NEEDS IMPROVEMENT      1
Name: count, dtype: int64

## Identify Incorrect Data Types

In [24]:
df.dtypes

Employee_ID                    int64
Name                             str
Age                           object
Gender                           str
Department                       str
City                             str
Salary                        object
Joining_Date          datetime64[us]
Experience_Years               int64
Email                            str
Performance_Rating               str
dtype: object

In [25]:
df["Age"].unique()

array([22, 26, 38, 42, 55, 25, 44, nan, 24, 34, 52, 45, 21, 33, 28, 48,
       49, 35, 23, 29, 27, 32, 31, 47, 36, 54, 53, 30, 46, 40, 41, 39,
       'twenty-six', 50, 43, 37, 51, '29 years', 'thirty-two', '41'],
      dtype=object)

In [26]:
df["Salary"].unique()

array([54256, 28905, 110181, 116506, 37676, 97357, 35458, 52460, 85589,
       77581, 109259, 101484, 45033, 94352, 69587, nan, 95697, 32592,
       41828, 115422, 57493, 34305, 92391, 86953, 80519, 57591, 34880,
       78269, 59760, 53534, 94615, 40713, 93522, 113039, 38104, 73434,
       111951, 52607, 37097, 59335, 44536, 65404, '₹55000', 68540, 54154,
       68025, 28617, 70309, 49914, 81531, 65538, 74695, 64829, 113555,
       37240, 87277, 77383, 31582, 103047, 45861, 82654, 43136, 27560,
       95545, 75968, 76645, 31590, 80255, 33993, 41544, 46992, 100470,
       116382, 73571, 108307, 95539, 61559, 67600, 61211, 115519, 115673,
       97140, 50242, 103222, 117801, 89340, 58092, 44555, 54581, 32894,
       56439, 63175, 106927, 43643, 115266, 103385, 100392, 82963, 68687,
       111846, 90338, 88532, 78476, 117459, 49983, 25336, 95592, 116422,
       74968, 38154, 86537, 66505, 36846, 32355, '65000', 101435, 62700,
       80615, 56091, 26061, 71179, 109717, 63680, 94579, 86385, 59663,
       113452, 33285, 64893, 112881, 105694, 72537, 41011, 41505, 44340,
       111646, 31868, 92271, 85036, 118375, 106830, 104354, 79239, 73843,
       71346, 91507, 40058, 48647, 111159, 74308, 103148, 83079, 39918,
       53903, 62938, 117231, 35205, 27733, 82104, 35011, 109599, 110918,
       108269, 64691, 29929, 97655, 84050, 57472, 75779, 68213, 111980,
       98259, 72425, 54693, 94013, 115812, 105031, 73213, 46241, 38446,
       44313, 90799, 118677, 43191, 44597, 56252, 107831, 71244, 96313,
       58246, 68583, 87722, 51144, 77431, 35828, 38447, 83606, 112973,
       82432, 104310, 43047, 49385, 83493, 84250, 96063, 51342, 105209,
       34666, 108859, 45056, 57847, 47103, 28718, 107203, 115257, 43830,
       98616, 37689, 100718, 90191, 31377, 81482, 98638, 'Rs. 72000',
       72920, 68652, 66750, 89205, 101507, 54824, 100047, 115505, 111799,
       71437, 98464, 44198, 87793, 101917, 38133, 110575, 110498, 49420,
       109058, 68343, 99420, 67982, 59181, 59282, 114925, 53721, 95453,
       117244, 44641, 32292, 65392, 80534, 78591, 74236, 94316, 94721,
       39790, 102849, 53477, 67030, 32989, 112994, 49101, 98713, 35363,
       104294, 64739, 51805, 59283, 73589, 101550, 99683, 71160, 112584,
       53668, 25866, 62576, 50156, 74436, 109529, 60532, 52152, 76007,
       37803, 108115, 49345, 34634, 36995, 81489, 103240, 98339, 60180,
       35082, 64932, 110332, 77198, 72843, 85505, 108012, 83860, 116964,
       98822, 54098, 90597, 43569, 37795, 69967, 98380, 28826, 61483,
       50830, 75939, 117535, 40328, 75293, 62858, 88518, 118079, 29285,
       100066, 38423, 82549, 81120, 61842, 114037, 44168, 60221, 61467,
       85089, 89843, 114463, 84836, 110798, 116677, 115968, 66071, 26110,
       105750, 75335, 97534, 91784, 56599, 99498, 59365, 80518, '85000',
       110175, 81948, 26487, 60227, 118365, 99302, 30772, 97465, 35208,
       77550, 73354, 50614, 70406, 51895, 30754, 37527, 63230, 34789,
       78282, 36851, 36955, 47789, 43322, 114952, 33450, 31637, 71392,
       105868, 75202, 75134, 75905, 86824, 94951, 56005, 98807, 32362,
       51406, 43566, 64552, 105440, 25235, 53953, 70457, 57707, 80004,
       100766, 27631, 34830, 110673, 78645, 76498, 63607, 63248, 109130,
       59510, 79870, 118625, 41539, 58801, 93116, 101372, 110824, 104777,
       87287, 114764, 109614, 32367, 99537, 72235, 29005, 97264, 46352,
       27628, 65037, 86171, 109848, 108964, 32441, 59003, 95075, 98170,
       114091, 68426, 106350, 32086, 48639, 84251, 105541, 94963, 25540,
       90973, 93195, 46611, 91143, 106675, 83237, 80164, 119210, 59471,
       90058, 100255, 109454, 63085, 43139, 37183, 115426, 38593, 105131,
       33301, '₹ 91000', 46679, 54190, 83733, 77879, 110799, 98420, 54064,
       46516, 53257, 108000, 94515, 100832, 104822, 43111, 53487, 96105,
       99794, 93515, 62567, 72013, 62701], dtype=object)

In [27]:
print(df["Joining_Date"].dtype)

datetime64[us]

## Data Cleaning

In [28]:

print("Duplicates before cleaning:", df.duplicated().sum())


df = df.drop_duplicates()

print("Duplicates after cleaning:", df.duplicated().sum())
print("Dataset shape after removing duplicates:", df.shape)

Duplicates before cleaning: 10
Duplicates after cleaning: 0
Dataset shape after removing duplicates: (490, 11)

In [29]:


text_columns = [
    "Name",
    "Gender",
    "Department",
    "City",
    "Email",
    "Performance_Rating"
]

for column in text_columns:
    df[column] = df[column].str.strip()

In [30]:
# Standardize Department values

df["Department"] = df["Department"].str.lower()

df["Department"] = df["Department"].replace({
    "it": "IT",
    "hr": "HR",
    "finance": "Finance",
    "marketing": "Marketing",
    "sales": "Sales",
    "operations": "Operations",
    "data analytics": "Data Analytics"
})

In [31]:
df["Department"].value_counts(dropna=False)

Department
Marketing         85
Sales             71
HR                68
Operations        66
IT                66
Finance           66
Data Analytics    61
NaN                7
Name: count, dtype: int64

In [32]:
# Standardize Gender values

df["Gender"] = df["Gender"].str.lower()

df["Gender"] = df["Gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female",
    "other": "Other"
})

In [33]:
df["Gender"].value_counts(dropna=False)

Gender
Male      176
Female    163
Other     151
Name: count, dtype: int64

In [34]:
# Standardize City values

df["City"] = df["City"].str.title()

In [35]:
df["City"].value_counts(dropna=False)

City
Dehradun      57
Jaipur        55
Gurugram      53
Chandigarh    52
Mumbai        51
Haridwar      50
Noida         47
Lucknow       43
Delhi         42
Bengaluru     40
Name: count, dtype: int64

In [36]:
# Standardize Performance Rating values

df["Performance_Rating"] = (
    df["Performance_Rating"]
    .str.strip()
    .str.title()
)

In [37]:
df["Performance_Rating"].value_counts()

Performance_Rating
Needs Improvement    142
Average              127
Good                 115
Excellent            106
Name: count, dtype: int64

In [38]:
# Correct inconsistent Age values

df["Age"] = df["Age"].replace({
    "twenty-six": 26,
    "29 years": 29,
    "thirty-two": 32
})

# Convert Age to numeric
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [39]:
df["Age"].dtype

dtype('float64')

In [ ]:
# Remove currency symbols and text from Salary

df["Salary"] = (
    df["Salary"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.strip()
)

df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [41]:
df["Salary"].dtype

dtype('float64')

In [42]:
# Handle missing values

# Fill missing Age with median age
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Salary with median salary
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

# Fill missing Department with Unknown
df["Department"] = df["Department"].fillna("Unknown")

# Fill missing Joining Date with median date
median_date = df["Joining_Date"].dropna().median()
df["Joining_Date"] = df["Joining_Date"].fillna(median_date)

In [43]:
# Convert Joining_Date to datetime

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

In [44]:
df["Joining_Date"].dtype

dtype('<M8[us]')

In [45]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("\nDataset shape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate records:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

========== FINAL DATA QUALITY CHECK ==========

Dataset shape:
(490, 11)

Missing values:
Employee_ID           0
Name                  0
Age                   0
Gender                0
Department            0
City                  0
Salary                0
Joining_Date          0
Experience_Years      0
Email                 0
Performance_Rating    0
dtype: int64

Duplicate records:
0

Data types:
Employee_ID                    int64
Name                             str
Age                          float64
Gender                           str
Department                       str
City                             str
Salary                       float64
Joining_Date          datetime64[us]
Experience_Years               int64
Email                            str
Performance_Rating               str
dtype: object

In [46]:
print("Departments:")
print(df["Department"].unique())

print("\nGender:")
print(df["Gender"].unique())

print("\nCities:")
print(df["City"].unique())

print("\nPerformance Ratings:")
print(df["Performance_Rating"].unique())

Departments:
<StringArray>
[    'Operations',          'Sales', 'Data Analytics',             'IT',
             'HR',        'Finance',      'Marketing',        'Unknown']
Length: 8, dtype: str

Gender:
<StringArray>
['Male', 'Other', 'Female']
Length: 3, dtype: str

Cities:
<StringArray>
[  'Gurugram',    'Lucknow',      'Noida',      'Delhi',   'Dehradun',
 'Chandigarh',     'Jaipur',  'Bengaluru',     'Mumbai',   'Haridwar']
Length: 10, dtype: str

Performance Ratings:
<StringArray>
['Excellent', 'Good', 'Needs Improvement', 'Average']
Length: 4, dtype: str

In [47]:
df.head(10)

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
0,1,Tanvi Singh,22.0,Male,Operations,Gurugram,54256.0,2019-07-26,11,tanvi.singh1@company.com,Excellent
1,2,Vivek Mehta,26.0,Male,Sales,Lucknow,28905.0,2019-01-19,3,vivek.mehta2@company.com,Good
2,3,Rohan Patel,22.0,Other,Sales,Noida,110181.0,2025-11-12,8,rohan.patel3@company.com,Needs Improvement
3,4,Diya Negi,38.0,Male,Data Analytics,Delhi,116506.0,2022-09-28,5,diya.negi4@company.com,Average
4,5,Avni Gupta,42.0,Female,IT,Dehradun,37676.0,2022-01-10,5,avni.gupta5@company.com,Average
5,6,Aditya Negi,55.0,Male,IT,Lucknow,97357.0,2021-04-15,10,aditya.negi6@company.com,Average
6,7,Shivam Gupta,25.0,Female,IT,Noida,35458.0,2020-08-11,1,shivam.gupta7@company.com,Needs Improvement
7,8,Ishaan Negi,44.0,Female,HR,Chandigarh,52460.0,2025-07-08,4,ishaan.negi8@company.com,Excellent
8,9,Simran Verma,39.0,Male,Operations,Noida,85589.0,2022-04-04,4,simran.verma9@company.com,Good
9,10,Vivek Kumar,24.0,Female,HR,Delhi,77581.0,2021-01-01,1,vivek.kumar10@company.com,Good

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         490 non-null    int64
 1   Name                490 non-null    str
 2   Age                 490 non-null    float64
 3   Gender              490 non-null    str
 4   Department          490 non-null    str
 5   City                490 non-null    str
 6   Salary              490 non-null    float64
 7   Joining_Date        490 non-null    datetime64[us]
 8   Experience_Years    490 non-null    int64
 9   Email               490 non-null    str
 10  Performance_Rating  490 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(6)
memory usage: 42.2 KB

## Exporting the cleaned dataset

In [49]:
df.to_csv("cleaned_employee_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!