In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("CODSOFT_Task1_Employee_Data_500.xlsx")

df.head()

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
0,1,Tanvi Singh,22,Male,Operations,Gurugram,54256,2019-07-26,11,tanvi.singh1@company.com,Excellent
1,2,Vivek Mehta,26,Male,Sales,Lucknow,28905,2019-01-19,3,vivek.mehta2@company.com,Good
2,3,Rohan Patel,22,Other,Sales,Noida,110181,2025-11-12,8,rohan.patel3@company.com,Needs Improvement
3,4,Diya Negi,38,Male,Data Analytics,Delhi,116506,2022-09-28,5,diya.negi4@company.com,Average
4,5,Avni Gupta,42,Female,IT,Dehradun,37676,2022-01-10,5,avni.gupta5@company.com,Average

In [3]:
df.shape

(500, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         500 non-null    int64
 1   Name                500 non-null    str
 2   Age                 490 non-null    object
 3   Gender              500 non-null    str
 4   Department          493 non-null    str
 5   City                500 non-null    str
 6   Salary              490 non-null    object
 7   Joining_Date        494 non-null    datetime64[us]
 8   Experience_Years    500 non-null    int64
 9   Email               500 non-null    str
 10  Performance_Rating  500 non-null    str
dtypes: datetime64[us](1), int64(2), object(2), str(6)
memory usage: 43.1+ KB

In [5]:
df.describe(include="all")

,Employee_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Experience_Years,Email,Performance_Rating
count,500.000000,500,490.0,500,493,500,490.0,494,500.000000,500,500
unique,NaN,316,39.0,10,21,19,480.0,NaN,NaN,490,8
top,NaN,Ayush Negi,39.0,Male,Marketing,Dehradun,57591.0,NaN,NaN,vivek.singh26@company.com,Needs Improvement
freq,NaN,5,21.0,176,84,55,2.0,NaN,NaN,2,145
mean,244.648000,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-09 02:28:39.838056,6.106000,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-03 00:00:00,0.000000,NaN,NaN
25%,122.000000,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-09 00:00:00,3.000000,NaN,NaN
50%,244.500000,NaN,NaN,NaN,NaN,NaN,NaN,2022-02-22 12:00:00,6.000000,NaN,NaN
75%,367.250000,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-30 00:00:00,9.000000,NaN,NaN
max,490.000000,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-20 00:00:00,12.000000,NaN,NaN
std,141.541301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.707054,NaN,NaN

In [6]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                   10
Gender                 0
Department             7
City                   0
Salary                10
Joining_Date           6
Experience_Years       0
Email                  0
Performance_Rating     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(10)

In [8]:
df["Department"].unique()
df["Gender"].unique()
df["City"].unique()
df["Performance_Rating"].unique()

<StringArray>
[        'Excellent',              'Good', 'Needs Improvement',
           'Average',         'excellent',            ' Good ',
           'average', 'NEEDS IMPROVEMENT']
Length: 8, dtype: str

In [9]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                   10
Gender                 0
Department             7
City                   0
Salary                10
Joining_Date           6
Experience_Years       0
Email                  0
Performance_Rating     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(10)

In [11]:
df.dtypes

Employee_ID                    int64
Name                             str
Age                           object
Gender                           str
Department                       str
City                             str
Salary                        object
Joining_Date          datetime64[us]
Experience_Years               int64
Email                            str
Performance_Rating               str
dtype: object

In [12]:
df.to_csv("cleaned_employee_data.csv", index=False)